CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    telegram_chat_id BIGINT,
		telegram_id BIGINT UNIQUE,
		google_id BIGINT UNIQUE,
		email VARCHAR(255),
		name VARCHAR(255),
		username VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS habits (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL REFERENCES users(id),
	key_name VARCHAR(255),
	type VARCHAR(255),
	label VARCHAR(255),
	emoji VARCHAR(255),
	order_index INT,
	active BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);